---
title: "Project Caffeine"
author: "Moretto"
date: "2022-11-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
normal<- data.frame(log(as.data.frame(Data_211_project$`amount total`)))
normal
ggplot(normal,aes(x= Data_211_project..amount.total.))+geom_histogram(color="black", fill="white")#+ geom_density(alpha=.2, fill="#FF6666")
```

```{r}
#Summary of table
Data_211_project%>%
  group_by
```

```{r}
#is my intake of caffeine significantly higher than the 400mg recommended
#by the FDA?
#Is there a correlation between the amount of caffeine from food and total caffeine intake?
Data<-Data_211_project%>%
  summarize(Average_Total=mean(`amount total`,na.rm = TRUE))

Data
Liquid<-Data_211_project%>%
  summarize(Average_liquid=mean(liquid,na.rm = TRUE))

Liquid

Food<-Data_211_project%>%
  summarize(Average_Food=mean(food,na.rm = TRUE))

Food

ggplot(Data_211_project,aes(x=Day, y=`amount total`))+geom_line()

ggplot(Data_211_project,aes(x=`amount total`))+geom_histogram(binwidth=3,color="black", fill="white")+ geom_density(alpha=.2, fill="#FF6666") 

ggplot(Data_211_project,aes(x= liquid))+geom_histogram(binwidth=3,color="black", fill="white")+ geom_density(alpha=.2, fill="#FF6666") 

ggplot(Data_211_project,aes(x=food))+geom_histogram(binwidth=3,color="black", fill="white")+ geom_density(alpha=.2, fill="#FF6666") 

```

```{r}
#Segment Caffeine Analysis

#H0: mu = 226
#Ha: mu > 226

t.test(Data_211_project$`amount total`,mu=226, alternative ="greater")

#There is insufficient evidence to reject the H0 that the subject's caffeine consumption is greater than the FDA recommended of 226

t.test(Data_211_project$`amount total`,mu=400, alternative ="greater")

#Total Caffeine Analysis

#H0: mu = 400
#Ha: mu > 400

t.test(Data_211_project$`amount total`,mu=400, alternative ="greater")

#There is sufficient evidence to reject the H0 that the subject's caffeine consumption is greater than the FDA recommended of 226.
```
```{r}
model1<-lm(`amount total`~liquid, data = Data_211_project)
summary(model1)
ggplot(data = Data_211_project, aes(x =`amount total`, y=liquid))+geom_point()+geom_smooth(method ="lm",se = FALSE)
model2<-lm(`amount total`~food, data = Data_211_project)
summary(model2)
ggplot(data = Data_211_project, aes(x =`amount total`, y=food))+geom_point()+geom_smooth(method ="lm",se = FALSE)

model3 <- lm(`amount total`~liquid+food, data=Data_211_project )
summary(model3)


```

